FROM php:7.4-apache

# Install PHP extensions
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# Copy app code
COPY . /var/www/html/

# Set permissions
RUN chown -R www-data:www-data /var/www/html
